source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/igordrljic/date-picker-ios.git'

platform :ios, '14.4'

target 'shunka-shop' do
  use_frameworks!
  pod 'SwiftGen', '~> 6.0'
end
